name: RandomEggs-OG
author: s0me0ne-coder
description: A paper plugin that makes the dragon egg generate with a 10% chance
website: https://github.com/s0me0ne-coder/RandomEggs-OG
version: 1.0
api-version: 1.18
main: plugin.RandomEggs
