name: ColorCodes-OG
author: NotAlexNoyle
description: A simple, helpful plugin to reveal bukkit's color codes for chat formatting.
website: https://github.com/NotAlexNoyle/ColorCodes-OG/
version: 1.0
api-version: 1.18
main: plugin.ColorCodesOG

commands:
  colorcodes:
    description: Reveal bukkit's color codes for chat formatting.
    aliases: [ccs]
